# Generated by Django 4.2.5 on 2023-10-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAuditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='UAP',
            field=models.CharField(default='Todas', max_length=3),
        ),
        migrations.AddField(
            model_name='sector',
            name='UAT',
            field=models.CharField(default='Todas', max_length=3),
        ),
    ]
